@startuml
'https://plantuml.com/class-diagram

abstract class Tariff
{
    decimal CalculatePayment();
}

Tariff <.. EconomyTariff
Tariff <.. ComfortTariff
Tariff <.. BusinessTariff
Tariff <.. EliteTariff

class DriverModel
{
    +Guid Id;
    +DriverInfo Info;
    +CarInfo CarInfo;
    +CartesianLocationUnit LocationUnit;
    +DriverRating Rating;
    +Tariff ConcreteTariff;
}

class DriverInfo
{
    +Guid Id;
    +string Name;
    +string Surname;
}

class DriverRating
{ 
    -List<OrderRating> _ratingHistory;
    +Guid Id;
    +decimal AvrRating;
    +IReadOnlyCollection<OrderRating> RatingHistory;
}

class OrderRating
{
    +Guid Id;
    +int GivenRating;
    +Passenger Author;
}

class CarInfo
{
    +Guid Id;
    +string ModelName;
    +string CarNumber;
    +string Color;
}

class CartesianLocationUnit
{
    +decimal Abscissa
    +decimal Ordinate
}

DriverModel o-- DriverRating
DriverModel o-- DriverInfo
DriverModel o-- CarInfo
DriverModel o-- CartesianLocationUnit
DriverModel o-d--- Tariff

DriverRating o-- OrderRating

@enduml